networks:
  events-network:

services:
  barsync-db:
    image: mysql:latest
    container_name: barsync-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: barsync-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-custom.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - events-network

  barsync-db-migration:
    image: ghcr.io/wildlight-tech/barsync-db-migration:latest
    platform: linux/amd64
    container_name: barsync-db-migration
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/barsync-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: verysecret
    depends_on:
      barsync-db:
        condition: service_started
    networks:
      - events-network

#  seed-migration:
#    image: ghcr.io/wildlight-tech/seed-migration:latest
#    container_name: seed-migration
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://barsync-mysql:3306/barsync_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: verysecret
#    depends_on:
#      barsync-db-migration:
#        condition: service_completed_successfully
#    networks:
#      - events-network
#
#  barsync-events-api:
#    image: ghcr.io/wildlight-tech/barsync-events-api:latest
#    container_name: barsync-events-api
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://barsync-mysql:3306/barsync_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: verysecret
#    depends_on:
#      seed-migration:
#        condition: service_completed_successfully
#    networks:
#      - events-network
#
#  barsync-aihg-frontend:
#    image: ghcr.io/wildlight-tech/barsync-aihg-frontend:latest
#    container_name: barsync-aihg-frontend
#    ports:
#      - "4200:80"
#    depends_on:
#      - barsync-events-api
#    networks:
#      - events-network

volumes:
  mysql_data: